version: '3'
services:
  app:
    build: .
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=dev
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    container_name: mysqlusers
    restart: always
    environment:
      MYSQL_DATABASE: 'profile'
      MYSQL_ROOT_USER: 'root'
      MYSQL_ROOT_PASSWORD: 'MyRoot12345!'
    ports:
      - '3306:3306'

